# ProjectInstall.cmake
# 安装与包导出生命周期入口
# 受 ENABLE_INSTALL 门控；生成 *Config.cmake 供下游 find_package 消费

function(oneq_configure_package_dependencies out_var)
    # 组装下游包配置文件中的 find_dependency(...) 片段：每个第三方包对应一行。
    # 依赖的 cmake config 文件会在安装时一并部署到 <prefix>/lib/cmake/1q/deps/，
    # 下游无需单独安装第三方包。
    set(config_find_dependencies "")
    if(PACKAGE_MANAGER STREQUAL "conan")
        string(APPEND config_find_dependencies
            "find_dependency(Eigen3 REQUIRED CONFIG)\n"
            "find_dependency(Boost REQUIRED CONFIG)\n"
            "find_dependency(nanoflann REQUIRED CONFIG)\n"
            "find_dependency(flatbuffers REQUIRED CONFIG)\n")
        # spdlog 仅在启用时纳入，避免下游被迫安装未使用的依赖。
        if(PROJECT_ENABLE_SPDLOG)
            string(APPEND config_find_dependencies
                "find_dependency(spdlog REQUIRED CONFIG)\n")
        endif()
        string(APPEND config_find_dependencies "find_dependency(ZLIB REQUIRED CONFIG)\n")
        # jsbsim 仅在启用 flight_dynamic 时纳入，默认关闭时不依赖。
        if(ONEQ_ENABLE_FLIGHT_DYNAMIC)
            string(APPEND config_find_dependencies
                "find_dependency(jsbsim REQUIRED CONFIG)\n")
        endif()
        # HDF5 输出能力依赖 HighFive，仅在 C++17 且包存在时启用。
        if(ONEQ_ENABLE_HDF5_OUTPUT)
            string(APPEND config_find_dependencies
                "find_dependency(HighFive REQUIRED CONFIG)\n")
        endif()
    endif()
    set("${out_var}" "${config_find_dependencies}" PARENT_SCOPE)
endfunction()

# 可移植第三方依赖配置：每个条目包含
#   data_file_prefix   conan data 文件名前缀（如 "Eigen3"）
#   var_prefix         data 文件中的变量名前缀（如 "eigen"）
#   config_file_name   生成的 cmake config 文件名（如 "Eigen3Config"）
#   target_name        CMake target 名（如 "Eigen3::Eigen"）
set(_portable_deps
    "Eigen3|eigen|Eigen3Config|Eigen3::Eigen"
    "Boost|boost|BoostConfig|Boost::boost"
    "nanoflann|nanoflann|nanoflann-config|nanoflann::nanoflann"
    "flatbuffers|flatbuffers|flatbuffers-config|flatbuffers::flatbuffers"
    "ZLIB|zlib|ZLIBConfig|ZLIB::ZLIB"
)

function(install_portable_dependency data_prefix var_prefix config_name target_name)
    if(NOT PACKAGE_MANAGER STREQUAL "conan")
        return()
    endif()

    # 读取 conan 数据文件，获取包路径
    set(_data_file "${CMAKE_BINARY_DIR}/build/generators/${data_prefix}-release-x86_64-data.cmake")
    if(NOT EXISTS "${_data_file}")
        message(WARNING "Conan data file not found: ${_data_file}")
        return()
    endif()

    include("${_data_file}")
    set(_inc_dirs "${${var_prefix}_INCLUDE_DIRS_RELEASE}")
    if(NOT _inc_dirs)
        message(WARNING "No INCLUDE_DIRS_RELEASE in ${_data_file}")
        return()
    endif()
    list(GET _inc_dirs 0 _inc_dir)

    # 安装第三方头文件到安装树
    install(DIRECTORY "${_inc_dir}/"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/deps/${var_prefix}")

    # 生成可移植的 cmake config 文件（路径指向安装树本地）
    set(_gen_dir "${CMAKE_BINARY_DIR}/_gen_deps_cmake")
    file(MAKE_DIRECTORY "${_gen_dir}")
    set(_config_path "${_gen_dir}/${config_name}.cmake")
    file(WRITE "${_config_path}"
        "# Generated by 1q install. Portable dependency config.\n"
        "if(NOT TARGET ${target_name})\n"
        "  add_library(${target_name} INTERFACE IMPORTED)\n"
        "  set_target_properties(${target_name} PROPERTIES\n"
        "    INTERFACE_INCLUDE_DIRECTORIES \"\${_IMPORT_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}/deps/${var_prefix}\")\n"
        "endif()\n")

    install(FILES "${_config_path}"
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/deps/")
endfunction()

function(oneq_install_project)
    if(NOT ENABLE_INSTALL)
        return()
    endif()

    include(CMakePackageConfigHelpers)

    # 安装核心 target 并关联到导出集，按 GNUInstallDirs 标准路径分类产物。
    install(TARGETS ${PROJECT_CORE_TARGET}
        EXPORT ${PROJECT_EXPORT_SET}
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    )

    # include/1q/ 是受控的公共头边界：镜像安装而非维护第二份模块本地头清单。
    install(DIRECTORY "${CMAKE_SOURCE_DIR}/include/1q/"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/1q"
        FILES_MATCHING
            PATTERN "*.h"
            PATTERN "*.hpp"
            PATTERN "README.md")
    install(FILES "${PROJECT_GENERATED_EXPORT_HEADER}"
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/1q
    )

    # 导出 target 集为 <PROJECT_NAME>Targets.cmake，下游以 <PROJECT_NAME>:: 命名空间引用。
    install(EXPORT ${PROJECT_EXPORT_SET}
        NAMESPACE ${PROJECT_NAME}::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
        FILE ${PROJECT_NAME}Targets.cmake
    )

    # 生成 *Config.cmake.in 模板并 configure 为最终包配置文件。
    oneq_configure_package_dependencies(ONEQ_CONFIG_FIND_DEPENDENCIES)
    set(_oneq_config_template "${CMAKE_BINARY_DIR}/${PROJECT_NAME}Config.cmake.in")
    file(WRITE "${_oneq_config_template}" [=[@PACKAGE_INIT@

include(CMakeFindDependencyMacro)

# 下游无需单独安装第三方依赖——cmake 配置文件与头文件均已本地部署。
list(APPEND CMAKE_PREFIX_PATH "${CMAKE_CURRENT_LIST_DIR}/deps")

@ONEQ_CONFIG_FIND_DEPENDENCIES@

include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@Targets.cmake")

if(MSVC AND TARGET @PROJECT_NAME@::@PROJECT_NAME_LOWER@)
    set_property(TARGET @PROJECT_NAME@::@PROJECT_NAME_LOWER@ PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
endif()

check_required_components(@PROJECT_NAME@)

set(@PROJECT_NAME@_VERSION @PROJECT_VERSION@)
set(@PROJECT_NAME@_INCLUDE_DIRS "@PACKAGE_CMAKE_INSTALL_INCLUDEDIR@")
set(@PROJECT_NAME@_LIBRARIES @PROJECT_NAME@::@PROJECT_NAME_LOWER@)
]=])

    configure_package_config_file(
        "${_oneq_config_template}"
        "${CMAKE_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
        INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
        PATH_VARS CMAKE_INSTALL_INCLUDEDIR
    )

    # 版本兼容策略采用 SameMajorVersion：次版本/补丁升级视为兼容，主版本升级需人工确认。
    write_basic_package_version_file(
        "${CMAKE_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion
    )

    # 安装两个配置文件到 cmake/ 目录，下游 find_package 即可定位。
    install(FILES
        "${CMAKE_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
        "${CMAKE_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
    )

    # 清理旧的 conan 生成 deps cmake 文件，替换为可移植版本。
    # 先安装第三方头文件 + 生成可移植 cmake config。
    foreach(_dep IN LISTS _portable_deps)
        string(REPLACE "|" ";" _parts "${_dep}")
        list(GET _parts 0 _dp)
        list(GET _parts 1 _vp)
        list(GET _parts 2 _cf)
        list(GET _parts 3 _tn)
        install_portable_dependency("${_dp}" "${_vp}" "${_cf}" "${_tn}")
    endforeach()

    # 移除旧的 conan 生成 cmake 文件（已被可移植版替代），保留 cmakedeps_macros（可能仍被引用）。
    install(CODE "file(REMOVE_RECURSE \"\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/deps/cmakedeps_macros.cmake\")")
endfunction()
