# Explicit lifecycle helpers for the top-level CMakeLists.txt. Macros are used
# deliberately: CMake's directory-level output/test/install settings must be
# written in the caller's directory scope.

set(ONEQ_PROJECT_SETUP_DIR "${CMAKE_CURRENT_LIST_DIR}")

macro(oneq_prepare_project)
    if(DEFINED CMAKE_TOOLCHAIN_FILE)
        get_filename_component(_requested_toolchain "${CMAKE_TOOLCHAIN_FILE}" ABSOLUTE)
        if(NOT EXISTS "${_requested_toolchain}")
            message(FATAL_ERROR
                "Requested toolchain does not exist: ${CMAKE_TOOLCHAIN_FILE}\n"
                "请先运行 scripts/bootstrap_conan.sh <preset> 生成 conan_toolchain.cmake，"
                "再执行 cmake --preset <preset>。")
        endif()
    endif()

    set(PROJECT_DEFAULT_CXX_STANDARD 17)
    if(DEFINED CMAKE_CXX_STANDARD AND NOT CMAKE_CXX_STANDARD STREQUAL "")
        set(PROJECT_CXX_STANDARD "${CMAKE_CXX_STANDARD}")
    else()
        set(PROJECT_CXX_STANDARD "${PROJECT_DEFAULT_CXX_STANDARD}")
    endif()
    if(PROJECT_CXX_STANDARD LESS 11)
        message(FATAL_ERROR "CMAKE_CXX_STANDARD must be at least 11")
    endif()

    if(POLICY CMP0091)
        cmake_policy(SET CMP0091 NEW)
    endif()
    if(POLICY CMP0092)
        cmake_policy(SET CMP0092 NEW)
    endif()
endmacro()

macro(oneq_configure_project)
    string(TOLOWER "${PROJECT_NAME}" PROJECT_NAME_LOWER)
    set(PROJECT_ALIAS "${PROJECT_NAME}::core")
    set(PROJECT_CORE_TARGET "${PROJECT_NAME_LOWER}_lib")
    set(PROJECT_EXPORT_SET "${PROJECT_NAME}Targets")

    include("${ONEQ_PROJECT_SETUP_DIR}/ProjectOptions.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/UnityBuild.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/CCache.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/ClangTidy.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/ClangFormat.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/Coverage.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/features/PrecompiledHeaders.cmake")
    include("${ONEQ_PROJECT_SETUP_DIR}/codegen/FlatBuffers.cmake")
    if(MSVC)
        include("${CMAKE_SOURCE_DIR}/cmake/compilers/CompilerMSVC.cmake")
    else()
        include("${CMAKE_SOURCE_DIR}/cmake/compilers/CompilerClangGCC.cmake")
    endif()

    include("${ONEQ_PROJECT_SETUP_DIR}/ProjectDependencies.cmake")
    include("${ONEQ_PROJECT_SETUP_DIR}/ProjectInstall.cmake")
    include("${ONEQ_PROJECT_SETUP_DIR}/ProjectTargets.cmake")
    include("${ONEQ_PROJECT_SETUP_DIR}/ProjectSummary.cmake")
    include("${ONEQ_PROJECT_SETUP_DIR}/legacy/Vs2015SourceNormalization.cmake")

    oneq_configure_project_environment()
    oneq_find_project_dependencies()
    oneq_configure_project_outputs()
    oneq_configure_project_facilities()
endmacro()

macro(oneq_configure_project_environment)
    set(CMAKE_CXX_STANDARD "${PROJECT_CXX_STANDARD}")
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

    get_property(ONEQ_IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(ONEQ_IS_MULTI_CONFIG)
        message(STATUS "Multi-config generator detected (${CMAKE_GENERATOR})")
        if(NOT "RelWithDebInfo" IN_LIST CMAKE_CONFIGURATION_TYPES)
            list(APPEND CMAKE_CONFIGURATION_TYPES RelWithDebInfo)
        endif()
    else()
        if(NOT CMAKE_BUILD_TYPE)
            set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build" FORCE)
        endif()
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS
            "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
        message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
    endif()

    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        message(WARNING "32-bit compilation detected. This may not be fully supported.")
    endif()
endmacro()

macro(oneq_configure_project_outputs)
    if(ONEQ_IS_MULTI_CONFIG)
        foreach(ONEQ_OUTPUT_CONFIG IN LISTS CMAKE_CONFIGURATION_TYPES)
            string(TOUPPER "${ONEQ_OUTPUT_CONFIG}" ONEQ_OUTPUT_CONFIG_UPPER)
            set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${ONEQ_OUTPUT_CONFIG_UPPER} "${CMAKE_BINARY_DIR}/${ONEQ_OUTPUT_CONFIG}/lib")
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${ONEQ_OUTPUT_CONFIG_UPPER} "${CMAKE_BINARY_DIR}/${ONEQ_OUTPUT_CONFIG}/lib")
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${ONEQ_OUTPUT_CONFIG_UPPER} "${CMAKE_BINARY_DIR}/${ONEQ_OUTPUT_CONFIG}/bin")
        endforeach()
    else()
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
    endif()
endmacro()

macro(oneq_configure_project_facilities)
    if(ENABLE_TESTING)
        include(CTest)
        enable_testing()
    endif()

    if(ENABLE_INSTALL)
        include(GNUInstallDirs)
        if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
            set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE PATH "Installation prefix" FORCE)
        endif()
    endif()
endmacro()
