# SAR source manifest shared by production targets and contract checks.

set(SAR_ENGINE_SOURCES
    sar/calibration/SarRadiometricCalibration.cpp
    sar/echo/SarEcho.cpp
    sar/geometry/SarAntenna.cpp
    sar/geometry/SarGeometry.cpp
    sar/geometry/SarScanBurst.cpp
    sar/geometry/SarSpotlightBeam.cpp
    sar/imaging/SarAutofocusPhaseTruth.cpp
    sar/imaging/SarFocusingSelector.cpp
    sar/imaging/SarGbp.cpp
    sar/imaging/SarImageQuality.cpp
    sar/imaging/SarMotionCompensation.cpp
    sar/imaging/SarMultilook.cpp
    sar/imaging/SarOmegaKAzimuthInverseTransform.cpp
    sar/imaging/SarOmegaKCommonSupport.cpp
    sar/imaging/SarOmegaKFocusing.cpp
    sar/imaging/SarOmegaKGeometry.cpp
    sar/imaging/SarOmegaKGridReduction.cpp
    sar/imaging/SarOmegaKPointTargetAcceptance.cpp
    sar/imaging/SarOmegaKReducedRangeAxis.cpp
    sar/imaging/SarOmegaKReferenceMapping.cpp
    sar/imaging/SarOmegaKReferencePhaseCompensation.cpp
    sar/imaging/SarOmegaKRelativeDelayTransform.cpp
    sar/imaging/SarOmegaKSpectrumFrontEnd.cpp
    sar/imaging/SarOmegaKStoltInterpolation.cpp
    sar/imaging/SarOmegaKTruthEligibility.cpp
    sar/imaging/SarOmegaKTruthEvaluationOrchestrator.cpp
    sar/imaging/SarOmegaKTruthIngestion.cpp
    sar/imaging/SarOmegaKTruthManifest.cpp
    sar/imaging/SarOmegaKTruthPayloadDigest.cpp
    sar/imaging/SarPhaseReference.cpp
    sar/imaging/SarPgaSupportGradientTruth.cpp
    sar/imaging/SarPgaPhaseGradientEstimator.cpp
    sar/imaging/SarPgaGradientTruthComparison.cpp
    sar/imaging/SarRda.cpp
    sar/output/ImageFormatter.cpp
    sar/imaging/SarScanSarFocusing.cpp
    sar/imaging/SarSlowTimeResampling.cpp
    sar/imaging/SarSlowTimeResamplingExecutor.cpp
    sar/runtime/PulseRingBuffer.cpp
    sar/signal/SarFft.cpp
    sar/signal/SarWaveform.cpp
)

set(SAR_CORE_SOURCES
    sar/session/SarDiagnosticUtils.cpp
    sar/session/SarInputValidation.cpp
    sar/session/SarRawHistoryBuilder.cpp
    sar/session/SarReplayFlatbufferCodec.cpp
    sar/session/SarRuntimeConfigResolver.cpp
    sar/session/SarRuntimeConfigValidation.cpp
    sar/session/SarSessionConfigValidation.cpp
    sar/session/SarFocusedImageAssembler.cpp
    sar/session/SarImagingExecutor.cpp
    sar/session/SarProductDebugViewBuilder.cpp
    sar/session/SarProductLifecycleRecorder.cpp
    sar/pipeline/SarProcessingPipeline.cpp
    sar/runtime/SarController.cpp
    sar/session/SarSession.cpp
    sar/session/SarSessionCompositionRoot.cpp
    sar/session/SarTraceSession.cpp
    sar/session/SarReplaySession.cpp
)

set(SAR_CXX11_COMPAT_SOURCES
    ${SAR_ENGINE_SOURCES}
    sar/session/SarDiagnosticUtils.cpp
    sar/session/SarRuntimeConfigValidation.cpp
    sar/session/SarRawHistoryBuilder.cpp
    sar/session/SarFocusedImageAssembler.cpp
    sar/session/SarImagingExecutor.cpp
    sar/pipeline/SarProcessingPipeline.cpp
    sar/runtime/SarController.cpp
    sar/session/SarSession.cpp
    sar/session/SarSessionCompositionRoot.cpp
)
