#!/usr/bin/env python3
"""Plot racetrack approach trajectories for all scenarios.

Usage: python3 plot_racetrack_approach.py [csv_dir] [output.png]

Reads CSV files generated by racetrack_approach_trace and plots
all trajectories overlaid on the ideal racetrack shape.
"""

import csv
import sys
import os
import re
import math
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# Scenario display config
SCENARIO_CFG = {
    'aligned':     {'color': '#2ecc71', 'ls': '-',  'lw': 1.8, 'label': 'Aligned (baseline)'},
    'behind':      {'color': '#3498db', 'ls': '-',  'lw': 1.2, 'label': 'Behind 5km'},
    'left_side':   {'color': '#e67e22', 'ls': '-',  'lw': 1.2, 'label': 'Left 5km'},
    'right_side':  {'color': '#9b59b6', 'ls': '-',  'lw': 1.2, 'label': 'Right 5km'},
    'far_behind':  {'color': '#1abc9c', 'ls': '--', 'lw': 1.0, 'label': 'Behind 10km'},
    'far_right':   {'color': '#e74c3c', 'ls': '--', 'lw': 1.0, 'label': 'Right 10km'},
    'diagonal_se': {'color': '#f39c12', 'ls': '-.', 'lw': 1.0, 'label': 'SE diagonal 5km'},
    'diagonal_nw': {'color': '#8e44ad', 'ls': '-.', 'lw': 1.0, 'label': 'NW diagonal 5km'},
}


def parse_header(header_line):
    """Extract r and leg from CSV header comment."""
    m = re.search(r'r=([\d.]+).*leg=([\d.]+)', header_line)
    if m:
        return float(m.group(1)), float(m.group(2))
    return 1000.0, 10000.0


def read_csv(path):
    """Read a trace CSV, return list of dicts."""
    rows = []
    header = ''
    with open(path, 'r') as f:
        for line in f:
            if line.startswith('#'):
                header = line
                continue
            parts = line.strip().split(',')
            if len(parts) >= 6:
                try:
                    rows.append({
                        't': float(parts[0]),
                        'x': float(parts[1]),
                        'y': float(parts[2]),
                        'hdg': float(parts[3]),
                        'roll': float(parts[4]),
                        'err': float(parts[5]),
                    })
                except ValueError:
                    pass
    return rows, header


def draw_ideal_racetrack(ax, r, leg, color='gray', lw=2.0, alpha=0.5):
    """Draw the ideal racetrack shape."""
    # Leg1: x=0, y=[0, leg]
    ax.plot([0, 0], [0, leg], color=color, lw=lw, alpha=alpha, zorder=1)
    # Leg2: x=2r, y=[leg, 0]
    ax.plot([2*r, 2*r], [leg, 0], color=color, lw=lw, alpha=alpha, zorder=1)
    # Turn1: semicircle at (r, leg)
    theta1 = -90  # bottom of circle (at Leg1 end)
    theta2 = 90   # top of circle
    # CW from left to right: (0,leg) -> (2r,leg)
    # In matplotlib, Arc angles are CCW from East.
    # Bottom of circle = -90°, but we want the RIGHT semicircle
    # from (0,leg) at 180° CW to (2r,leg) at 0°
    # Actually: center=(r,leg), radius=r
    # (0,leg) is at angle 180° from center, (2r,leg) at angle 0°
    # CW from 180° to 0° = going through 270° (bottom)
    arc1 = patches.Arc((r, leg), 2*r, 2*r, angle=0,
                        theta1=270, theta2=90,
                        color=color, lw=lw, alpha=alpha, zorder=1)
    ax.add_patch(arc1)
    # Turn2: semicircle at (r, 0)
    # (2r,0) at angle 0° from center, (0,0) at angle 180°
    # CW from 0° to 180° = going through 270° (bottom, but this is
    # the bottom semicircle of the racetrack)
    # Wait: Turn2 CW from (2r,0) to (0,0) goes through the bottom
    # (r, -r). In Arc terms: from 0° CW to 180° through 270°
    # = from -90° to 90° in standard CCW terms
    arc2 = patches.Arc((r, 0), 2*r, 2*r, angle=0,
                        theta1=-90, theta2=90,
                        color=color, lw=lw, alpha=alpha, zorder=1)
    ax.add_patch(arc2)

    # Labels
    ax.annotate('Leg1 start', xy=(0, 0), xytext=(-800, -800),
                fontsize=8, color=color, alpha=0.7,
                arrowprops=dict(arrowstyle='->', color=color, alpha=0.4))
    ax.annotate('Turn1', xy=(r, leg+r*0.3), fontsize=7, color=color,
                alpha=0.5, ha='center')


def main():
    csv_dir = sys.argv[1] if len(sys.argv) > 1 else '/tmp/racetrack_approach_'
    output = sys.argv[2] if len(sys.argv) > 2 else '/tmp/racetrack_approach_plot.png'

    prefix = os.path.basename(csv_dir.rstrip('/'))

    fig, axes = plt.subplots(1, 2, figsize=(20, 10))
    fig.suptitle('Racetrack Approach Trajectories (c172p, r=1000m, leg=10000m)',
                 fontsize=14, fontweight='bold')

    ax_full = axes[0]
    ax_zoom = axes[1]
    ax_full.set_title('Full View', fontsize=12)
    ax_zoom.set_title('Track Area Zoom', fontsize=12)

    r = 1000.0
    leg = 10000.0

    # Draw ideal racetrack on both axes
    for ax in [ax_full, ax_zoom]:
        draw_ideal_racetrack(ax, r, leg, color='#333333', lw=2.5, alpha=0.6)
        ax.set_xlabel('x_prime (cross-track) [m]', fontsize=10)
        ax.set_ylabel('y_prime (along-track) [m]', fontsize=10)
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        ax.axhline(y=0, color='gray', lw=0.5, alpha=0.3)
        ax.axvline(x=0, color='gray', lw=0.5, alpha=0.3)

    ax_full.set_title('Full View', fontsize=12)
    ax_zoom.set_title('Track Area Zoom', fontsize=12)

    # Read and plot each scenario
    for name, cfg in SCENARIO_CFG.items():
        path = csv_dir + name + '.csv' if not csv_dir.endswith('/') else csv_dir + name + '.csv'
        if csv_dir.endswith('_'):
            path = csv_dir + name + '.csv'
        else:
            path = os.path.join(csv_dir, name + '.csv')

        if not os.path.exists(path):
            continue

        rows, header = read_csv(path)
        if not rows:
            continue

        if header:
            pr, pleg = parse_header(header)
            if pr > 0:
                r, leg = pr, pleg

        xs = [row['x'] for row in rows]
        ys = [row['y'] for row in rows]

        # Plot start marker
        ax_full.plot(xs[0], ys[0], 'o', color=cfg['color'], ms=5, zorder=5)
        ax_zoom.plot(xs[0], ys[0], 'o', color=cfg['color'], ms=5, zorder=5)

        # Plot trajectory
        ax_full.plot(xs, ys, color=cfg['color'], ls=cfg['ls'], lw=cfg['lw'],
                     label=cfg['label'], alpha=0.85, zorder=3)
        ax_zoom.plot(xs, ys, color=cfg['color'], ls=cfg['ls'], lw=cfg['lw'],
                     label=cfg['label'], alpha=0.85, zorder=3)

    # Set axis limits
    # Full view: show approach paths
    ax_full.set_xlim(-8000, 16000)
    ax_full.set_ylim(-14000, 16000)

    # Zoom: just the racetrack area with some margin
    margin = r * 3
    ax_zoom.set_xlim(-margin, 2*r + margin)
    ax_zoom.set_ylim(-margin, leg + margin)

    for ax in [ax_full, ax_zoom]:
        ax.legend(loc='upper left', fontsize=9, framealpha=0.9)

    plt.tight_layout()
    plt.savefig(output, dpi=150, bbox_inches='tight')
    print(f'Saved to {output}')

    # Also print convergence stats
    print('\n═══ Convergence Stats ═══')
    for name, cfg in SCENARIO_CFG.items():
        if csv_dir.endswith('_'):
            path = csv_dir + name + '.csv'
        else:
            path = os.path.join(csv_dir, name + '.csv')
        if not os.path.exists(path):
            continue
        rows, _ = read_csv(path)
        if not rows:
            continue
        errs = [row['err'] for row in rows]
        max_err = max(errs)
        avg_err = sum(errs) / len(errs)

        # Find converge time (first time err < 2*r)
        conv_t = None
        for row in rows:
            if row['err'] < 2 * r:
                conv_t = row['t']
                break

        # Post-convergence average
        post_errs = [row['err'] for row in rows if conv_t is not None and row['t'] >= conv_t]
        post_avg = sum(post_errs) / len(post_errs) if post_errs else avg_err

        conv_str = f'conv_time={conv_t:.1f}s' if conv_t is not None else 'NEVER CONVERGED'
        post_str = f'post_conv={post_avg:6.0f}m' if conv_t is not None else ''
        print(f'  {name:12s}  max_err={max_err:7.0f}m  avg_err={avg_err:7.0f}m  '
              f'{post_str}  {conv_str}')


if __name__ == '__main__':
    main()
