#!/usr/bin/env python3
"""Plot Figure-8 approach trajectories for all scenarios.

Usage: python3 plot_figure8_approach.py [csv_dir] [output.png]

Reads CSV files generated by figure8_approach_trace and plots
all trajectories overlaid on the ideal orbit circle.
"""

import csv
import sys
import os
import re
import math
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# Scenario display config
SCENARIO_CFG = {
    'aligned':       {'color': '#2ecc71', 'ls': '-',  'lw': 1.8, 'label': 'At center (baseline)'},
    'on_circle_s':   {'color': '#27ae60', 'ls': '-',  'lw': 1.8, 'label': 'On circle south (tangent)'},
    'behind':        {'color': '#3498db', 'ls': '-',  'lw': 1.2, 'label': 'South 5km'},
    'left_side':     {'color': '#e67e22', 'ls': '-',  'lw': 1.2, 'label': 'West 5km'},
    'right_side':    {'color': '#9b59b6', 'ls': '-',  'lw': 1.2, 'label': 'East 5km'},
    'far_behind':    {'color': '#1abc9c', 'ls': '--', 'lw': 1.0, 'label': 'South 10km'},
    'far_right':     {'color': '#e74c3c', 'ls': '--', 'lw': 1.0, 'label': 'East 10km'},
    'diagonal_se':   {'color': '#f39c12', 'ls': '-.', 'lw': 1.0, 'label': 'SE diagonal 5km'},
    'reverse_180':   {'color': '#8e44ad', 'ls': '-.', 'lw': 1.0, 'label': 'Reverse (heading south)'},
}


def parse_header(header_line):
    """Extract r and cycles from CSV header comment."""
    m = re.search(r'r=([\d.]+).*cycles=(\d+)', header_line)
    if m:
        return float(m.group(1)), int(m.group(2))
    return 1000.0, 3


def read_csv(path):
    """Read a trace CSV, return list of dicts."""
    rows = []
    header = ''
    with open(path, 'r') as f:
        for line in f:
            if line.startswith('#'):
                header = line
                continue
            parts = line.strip().split(',')
            if len(parts) >= 7:
                try:
                    rows.append({
                        't': float(parts[0]),
                        'north': float(parts[1]),
                        'east': float(parts[2]),
                        'hdg': float(parts[3]),
                        'roll': float(parts[4]),
                        'dist': float(parts[5]),
                        'bearing': float(parts[6]),
                    })
                except ValueError:
                    pass
    return rows, header


def draw_ideal_figure8(ax, r, color='gray', lw=2.0, alpha=0.5):
    """Draw the ideal figure-8: two tangent circles of radius r along the north-south axis.

    Center1 (CW lobe) at (r, 0) north of midpoint.
    Center2 (CCW lobe) at (-r, 0) south of midpoint.
    """
    # CW lobe: circle centered at (0, r) in (east, north) coords
    c1 = plt.Circle((0, r), r, fill=False, color=color,
                     lw=lw, alpha=alpha, ls='--', zorder=1)
    # CCW lobe: circle centered at (0, -r) in (east, north) coords
    c2 = plt.Circle((0, -r), r, fill=False, color=color,
                     lw=lw, alpha=alpha, ls='--', zorder=1)
    ax.add_patch(c1)
    ax.add_patch(c2)
    # Mark midpoint and centers
    ax.plot(0, 0, '+', color=color, ms=12, mew=2, alpha=alpha, zorder=1)
    ax.plot(0, r, 'x', color=color, ms=8, mew=1.5, alpha=alpha * 0.7, zorder=1)
    ax.plot(0, -r, 'x', color=color, ms=8, mew=1.5, alpha=alpha * 0.7, zorder=1)


def main():
    csv_dir = sys.argv[1] if len(sys.argv) > 1 else '/tmp/figure8_approach_'
    output = sys.argv[2] if len(sys.argv) > 2 else '/tmp/figure8_approach_plot.png'

    fig, axes = plt.subplots(1, 2, figsize=(20, 10))
    fig.suptitle('Figure-8 Approach Trajectories (c172p, r=1000m)',
                 fontsize=14, fontweight='bold')

    ax_full = axes[0]
    ax_zoom = axes[1]
    ax_full.set_title('Full View', fontsize=12)
    ax_zoom.set_title('Circle Area Zoom', fontsize=12)

    r = 1000.0

    # Read all data first to get r from headers
    all_data = {}
    for name, cfg in SCENARIO_CFG.items():
        path = os.path.join(csv_dir, name + '.csv') if not csv_dir.endswith('_') else csv_dir + name + '.csv'
        if not os.path.exists(path):
            continue
        rows, header = read_csv(path)
        if not rows:
            continue
        pr, _ = parse_header(header)
        if pr > 0:
            r = pr
        all_data[name] = (rows, cfg)

    # Draw ideal circle on both axes
    for ax in [ax_full, ax_zoom]:
        draw_ideal_figure8(ax, r, color='#333333', lw=2.5, alpha=0.6)
        ax.set_xlabel('east_m (from center)', fontsize=10)
        ax.set_ylabel('north_m (from center)', fontsize=10)
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        ax.axhline(y=0, color='gray', lw=0.5, alpha=0.3)
        ax.axvline(x=0, color='gray', lw=0.5, alpha=0.3)

    # Plot each scenario
    for name, (rows, cfg) in all_data.items():
        ns = [row['north'] for row in rows]
        es = [row['east'] for row in rows]

        # Plot start marker
        ax_full.plot(es[0], ns[0], 'o', color=cfg['color'], ms=5, zorder=5)
        ax_zoom.plot(es[0], ns[0], 'o', color=cfg['color'], ms=5, zorder=5)

        # Plot trajectory (east=north_m→x, north=east_m→y... wait)
        # CSV: north_m, east_m  → plot(east, north)
        ax_full.plot(es, ns, color=cfg['color'], ls=cfg['ls'], lw=cfg['lw'],
                     label=cfg['label'], alpha=0.85, zorder=3)
        ax_zoom.plot(es, ns, color=cfg['color'], ls=cfg['ls'], lw=cfg['lw'],
                     label=cfg['label'], alpha=0.85, zorder=3)

    # Set axis limits
    # Full view: show approach paths
    ax_full.set_xlim(-12000, 12000)
    ax_full.set_ylim(-14000, 6000)

    # Zoom: just the circle area with some margin
    margin = r * 3
    ax_zoom.set_xlim(-margin, margin)
    ax_zoom.set_ylim(-margin, margin)

    for ax in [ax_full, ax_zoom]:
        ax.legend(loc='upper left', fontsize=9, framealpha=0.9)

    plt.tight_layout()
    plt.savefig(output, dpi=150, bbox_inches='tight')
    print(f'Saved to {output}')

    # ── Convergence stats ──
    print('\n═══ Convergence Stats ═══')
    for name, (rows, cfg) in all_data.items():
        dists = [row['dist'] for row in rows]

        # Find convergence time: first time dist is within 10% of r
        conv_t = None
        for row in rows:
            if row['dist'] <= r * 1.2:  # within 20% of target radius
                conv_t = row['t']
                break

        # Post-convergence average distance and error
        post_dists = [row['dist'] for row in rows if conv_t is not None and row['t'] >= conv_t]
        if post_dists:
            avg_post = sum(post_dists) / len(post_dists)
            post_err = abs(avg_post - r)
            post_err_pct = post_err / r * 100
        else:
            avg_post = sum(dists) / len(dists)
            post_err = abs(avg_post - r)
            post_err_pct = post_err / r * 100

        # Bearing total rotation (detect CW/CCW cycles)
        bearings = [row['bearing'] for row in rows]
        total_bearing_change = 0.0
        for i in range(1, len(bearings)):
            db = bearings[i] - bearings[i-1]
            while db > math.pi: db -= 2 * math.pi
            while db < -math.pi: db += 2 * math.pi
            total_bearing_change += db
        total_bearing_deg = total_bearing_change * 180.0 / math.pi
        expected_deg = 360.0 * 3 * 2  # 3 full 8-cycles, each = CW360 + CCW360

        conv_str = f'conv_t={conv_t:.1f}s' if conv_t is not None else 'NEVER CONVERGED'
        post_str = f'post_err={post_err:.0f}m({post_err_pct:.1f}%)' if post_err is not None else ''
        print(f'  {name:14s}  avg_dist={avg_post:7.0f}m  bearing_total={total_bearing_deg:+8.1f}°'
              f'  ({total_bearing_deg/360:.1f} full turns)  {post_str}  {conv_str}')


if __name__ == '__main__':
    main()
